server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service?createDatabaseIfNotExist=true
    username: root
    password: An198205
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1b60018ab05d0d557a8d97e1006bc1c9dd2c8a9e17d82806a4a5e76c5b6a14e6"
  valid-duration: 3600 # in seconds token het han su dung (demo)
  refreshable-duration: 36000 # in seconds token duoc refrsh trong ..s sau khi het han su dung
